### PR TITLE
Bug beadtype memory leak

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
If I fix the memory leak here, the integration tests fail. 

      Start 14: Run_csg_fmatch
14/50 Test #14: Run_csg_fmatch .........................***Exception: SegFault  0.23 sec
      Start 15: Compare_csg_fmatch_output
15/50 Test #15: Compare_csg_fmatch_output ..............***Failed    0.03 sec
      Start 16: Run_csg_fmatch_3body
16/50 Test #16: Run_csg_fmatch_3body ...................***Exception: SegFault  0.23 sec
      Start 17: Compare_csg_fmatch_3body_output1
17/50 Test #17: Compare_csg_fmatch_3body_output1 .......***Failed    0.03 sec
      Start 18: Compare_csg_fmatch_3body_output2
18/50 Test #18: Compare_csg_fmatch_3body_output2 .......***Failed    0.03 sec
      Start 19: Compare_csg_fmatch_3body_output3
19/50 Test #19: Compare_csg_fmatch_3body_output3 .......***Failed    0.03 sec
      Start 20: Run_csg_map
20/50 Test #20: Run_csg_map ............................   Passed    0.03 sec
      Start 21: Compare_csg_map_output
21/50 Test #21: Compare_csg_map_output .................***Failed    0.05 sec
      Start 22: Run_csg_stat
22/50 Test #22: Run_csg_stat ...........................***Exception: SegFault  0.22 sec
      Start 23: Compare_csg_stat_output1
23/50 Test #23: Compare_csg_stat_output1 ...............***Failed    0.03 sec
      Start 24: Compare_csg_stat_output2
24/50 Test #24: Compare_csg_stat_output2 ...............***Failed    0.03 sec
      Start 25: Run_csg_stat_angular
25/50 Test #25: Run_csg_stat_angular ...................***Exception: SegFault  0.23 sec
      Start 26: Compare_csg_stat_angular_output
26/50 Test #26: Compare_csg_stat_angular_output ........***Failed    0.03 sec
      Start 27: Run_csg_stat-imc
27/50 Test #27: Run_csg_stat-imc .......................***Exception: SegFault  0.23 sec
      Start 28: Compare_csg_stat-imc_output
28/50 Test #28: Compare_csg_stat-imc_output ............***Failed    0.03 sec
      Start 29: Compare_csg_stat-imc_output_2
29/50 Test #29: Compare_csg_stat-imc_output_2 ..........***Failed    0.03 sec

### CODE REVIEW

**Comment by JensWehner** [comment]
What is this about, what does it change and what does it fix?

**Comment by JoshuaSBrown** [comment]
When the topology object was being deleted, the BeadType was originally created with new and the corresponding delete was not being called. This is a benign memory leak, as it is only leaked when a toplogy object is released, typically at the end of simulation. 

Instead, of using new the BeadTypes are now being stored directly in the vector. I think this fits with out discussion on slack earlier. The topology object owns the BeadTypes. These changes should not be braking the repo but they do for some other reason. It might be that once you merge your histogram stuff it fixes the problem.

**Comment by JensWehner** [comment]
Does the same not actually hold for the molecules and all the other data members as well?

@junghans are these vectors of pointers resorted somewhere, or why was this layout chosen?

**Comment by junghans** [comment]
@JensWehner, I don't know, maybe @ruehle remembers.

**Comment by JoshuaSBrown** [comment]
The topology object has a destructor it calls on everything but whoever wrote it failed to free the beadtypes, or it was at some point changed possibly by myself.

**Review by junghans — APPROVED** [review]

**Pull request merged**
