### PR TITLE
Lammps reader

### PR DESCRIPTION
**Pull request by JensWehner**
This PR does two things:

a) throw an error when votca tries to construct a bond between atoms from different molecules in the lammps reader.

b) at the moment unnamed molecules are named by their chemical composition, this can be problematic if we have isomers in the topology in that case an index is added at the end of the molecule.

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot format

**Comment by JensWehner** [comment]
@votca-bot changelog: reworked lammps molecule naming

**Comment by junghans** [comment]
This is more @JoshuaSBrown's cup of tea.

**Comment by JensWehner** [comment]
It is fully backwards compatible it just detects more errors than before.

**Review by junghans — APPROVED** [review]
Can you add a test?

**Comment by JensWehner** [comment]
Yes I will next week.

**Comment by JensWehner** [comment]
@votca-bot format

**Pull request merged**
