### PR TITLE
Stable fixes

### PR DESCRIPTION
**Pull request by junghans**
Fix #300

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
Ah, I see now.

**Comment by junghans** [comment]
You mainly need a new branch as the merge commit would go onto `stable` and we don't want that!

**Comment by JoshuaSBrown** [comment]
This is failing because of a LaTex error, I'm not quite sure what's with that.

**Comment by junghans** [comment]
It is because, he haven't merged the build fix from the  manual yet! Will fixed with https://github.com/votca/csg-manual/pull/10.

**Comment by junghans** [comment]
@JoshuaSBrown do you want to merge  the latest version of stable again?

**Comment by junghans** [comment]
@JoshuaSBrown I will do a new PR for that! (see #307)

**Pull request merged**
