### PR TITLE
also allow tab separators

### PR DESCRIPTION
**Pull request by JensWehner**

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot changelog: allow tab separators in xyz file

**Comment by JensWehner** [comment]
@votca-bot format

**Review by junghans — CHANGES_REQUESTED** [review]
The spec says whitespaces: http://openbabel.org/wiki/XYZ_%28format%29

**Comment by JensWehner** [comment]
you are right, I am getting lazy. :)

**Pull request closed without merging**
