### PR TITLE
Electrostatics corrected clang format

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
Only corrected format of the electrostatics branch. The wrong format file was being used it should be the same as the one in the votca/votca repo.

### CODE REVIEW

**Review by JensWehner — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
@JensWehner are you ok if I merge this even though it is not building with travis/gitlab etc?

**Comment by JoshuaSBrown** [comment]
@JensWehner

**Comment by JensWehner** [comment]
wait why is it failing gitlab?

**Comment by JensWehner** [comment]
I ran clang format with the correct clang format as well. Clang format beats me....

**Pull request merged**
