### PR TITLE
Made beadstructure a template

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
Bead structure was switched to a template class, and an error was fixed in beadmotif.

### CODE REVIEW

**Comment by JensWehner** [comment]
what was the error exactly?

**Comment by JensWehner** [comment]
this still does not fix the bug

**Comment by JoshuaSBrown** [comment]
The problem was InitializeGraph_() was not being called when calling get type. This means if the type was out of date it wasn't being updated to reflect the current type:

    BeadMotif::MotifType BeadMotif::getType() {
      if (!type_up_to_date_) {
        InitializeGraph_();
        CalculateType_();
      }
      return type_;
    }

**Comment by JoshuaSBrown** [comment]
@JensWehner Do I need to wait for you to take a closer look at this or are you good if I merge it?

**Comment by JensWehner** [comment]
please wait

**Comment by JoshuaSBrown** [comment]
Ok

**Review by JensWehner — APPROVED** [review]

**Pull request merged**
