### PR TITLE
Allow to change extrapolation function for lammps

### PR DESCRIPTION
**Pull request by junghans**
See: https://groups.google.com/d/msg/votca/FQlDlaWXsaA/_o1apQHxDwAJ

### CODE REVIEW

**Review by jdmoore2004 — APPROVED** [review]
Looks good to me.  I haven't tested it, because I wasn't sure how to download the fork, but I will look into it tomorrow.  This is a nice option to have.

**Comment by junghans** [comment]
You can do `git fetch origin pull/203/head && git checkout FETCH_HEAD`.

**Comment by jdmoore2004** [comment]
I'm not sure if I checked it out wrong, but I think I have the correct files.  I am getting

###############################################################################################################################
#                                                                                                                             #
# ERROR:                                                                                                                      #
# Unknown option '--lfct=sasha'                                                                                               #
# For details see the logfile /home/XXXX/inverse.log #
#                                                                                                                             #
###############################################################################################################################

Setting 

      <lammps>
        <table>table_b1.pot</table>
        <table_begin>2.0</table_begin>
        <table_end>8.0</table_end>
        <table_left_extrapolation>sasha</table_left_extrapolation>
        <table_right_extrapolation>sasha</table_right_extrapolation>
      </lammps>

Thanks.

**Comment by junghans** [comment]
Got it! Shell option parsing only works for `--lfct sasha` not `--lfct=sasha`. Give it another try.

**Comment by jdmoore2004** [comment]
Line 61 of potential_extrapolate.sh has an extra $

Change

is_part "${$2}" "${fct_types}" || die "${0##*/}: given function type ($2) is not in the list of functions (${fct_types})"

to

    is_part "${2}" "${fct_types}" || die "${0##*/}: given function type ($2) is not in the list of functions (${fct_types})"

Seems to work great otherwise.  Tested it on bonds for linear, quadratic, exponential and sasha left and right.

**Comment by junghans** [comment]
Typo fixed!

**Pull request merged**
