### PR TITLE
Remove all csg_get_*property() calls from Perl scripts

### LINKED ISSUE #179: Perl on Ubuntu 16.04 does not inherit exported shell functions
The perl behavior on Ubuntu 16.04 (perl-5.22.2-1) has changed:

```
$ bash
$ fct() { echo "Hello from within function";}
$ export -f fct
$ perl -e '$x=`bash -c "fct"`; print $x'
bash: fct: command not found
```

In contrast in early versions (e.g. Ubuntu 14.04):

```
$ bash
$ fct() { echo "Hello from within function";}
$ export -f fct
$ perl -e '$x=`bash -c "fct"`; print $x'
Hello from within function
```

However on Fedora 23 (perl-5.22.1) and Gentoo (perl-5.22.2) it works as expected.

This was found by a user here: https://groups.google.com/d/msg/votca/MnIiwjO3iC4/ceda5If3AgAJ

### PR DESCRIPTION
**Pull request by abrukhno**
Fix #179

### CODE REVIEW

**Comment by JensWehner** [comment]
Hey Andrey,

a pull request is basically you asking the project/the head developer to pull your changes to the branch you specified( most often the master). Most projectleaders head developers strongly dislike anybody without consent pushing stuff in the master branch (sometimes it is even not possible), so instead you open a pull request and if your changes are approved, they will be pulled into the master.

**Comment by abrukhno** [comment]
Hello Jens,
Many thanks for clarifying this! 
I will try now.
Andrey

**Comment by junghans** [comment]
`pressure_cor_wjk.pl` and `kbibi_ramp_correction.pl` still missing.

**Review by symashayak — COMMENTED** [review]
So far looks good to me.

**Comment by junghans** [comment]
The build break was excepted due to #220.

**Comment by junghans** [comment]
@abrukhno: please review

**Pull request merged**
