### PR TITLE
lammpswriter: initial commit

### PR DESCRIPTION
**Pull request by junghans**
Dump is nice because it is text-based and it supports force, which should be useful to add some test down the road.

### CODE REVIEW

**Review by JoshuaSBrown — CHANGES_REQUESTED** [review]
Looks great to me, but you don't have any tests, could we build in a simple test?

**Comment by junghans** [comment]
Good point, but I want to use `votca_compare` (votca/tools#43) for that.

**Review by JoshuaSBrown — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
Sounds good, you're the best!

**Comment by junghans** [comment]
@JoshuaSBrown, test added!

**Pull request merged**
