### PR TITLE
Change molecule stable vector to  boost deque

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
As per my performance analysis boost deque is the way to go.

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
@JoshuaSBrown more conflicts.

**Comment by JoshuaSBrown** [comment]
Are you in a rush for something?

**Comment by junghans** [comment]
@votca-bot format

**Comment by junghans** [comment]
> Are you in a rush for something?

I just don't want these things to become stale.

Also more conflicts ;-)

**Comment by junghans** [comment]
@votca-bot format

**Pull request merged**
