### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
I don't know if this is the correct way to do this, but I'm guessing we want to pull in the bug fixes from stable into master?

### CODE REVIEW

**Comment by junghans** [comment]
There are a bunch of conflicts here!

**Comment by JoshuaSBrown** [comment]
So what is the normal procedure, do you cherrypick?

**Comment by junghans** [comment]
No, merging is right, you just need to resolve the conflicts.

**Comment by junghans** [comment]
Is it never good to use the stable branch directly, see #301.

Leave this PR open for now.

**Pull request closed without merging**
