### PR TITLE
fix multicomponent csg_stat_imc

### LINKED ISSUE #577: IMC multicomponent working?
Is there a working implementation of multicomponent IMC?

I'm trying with csg-tutorials/propane/imc, but only A-A gets updated. I took a look in src/tools/csg_stat_imc.cc, but with my low C++ skills I can't tell if multicomponent sampling of the IMC matrix is implemented or not. The resulting matrix all.gmc is zero everywhere except for the A-A block.

### PR DESCRIPTION
**Pull request by marvinbernhardt**
fix https://github.com/votca/csg/issues/577

### CODE REVIEW

**Comment by junghans** [comment]
@DRosen285 can you check that makes it work again for your example.

I will add a test to this as well.

**Review by JensWehner — APPROVED** [review]
LGTM

**Review by DRosen285 — APPROVED** [review]

**Comment by DRosen285** [comment]
> @DRosen285 can you check that makes it work again for your example.
> 
> I will add a test to this as well.

Works

**Comment by marvinbernhardt** [comment]
Sorry my git understanding is limited. Did this get merged?

**Comment by junghans** [comment]
I want to push it to stable instead, see #579

**Comment by junghans** [comment]
> Sorry my git understanding is limited. Did this get merged?

No worries, I think this fix is worth adding to stable and maybe even to push out a v1.6.2 release, thanks again for finding and fixing the bug!

**Pull request closed without merging**
