### PR TITLE
CHANGELOG.md: update

### PR DESCRIPTION
**Pull request by junghans**
@jens, you need to do the same for xtp.

Should we do that for tools as well?

### CODE REVIEW

**Review by JoshuaSBrown — APPROVED** [review]

**Comment by JoshuaSBrown** [comment]
I suppose we could do something similar for tools. I have added the beginnings of some graph functionality. We have also updated the histogram class + all the stuff @JensWehner did with switching to Eigen.

**Comment by junghans** [comment]
Are you volunteering?

**Comment by JensWehner** [comment]
I ll do the xtp part, if joshua is happy to do it for tools?

**Comment by JoshuaSBrown** [comment]
I can give it a shot but I'm leaving for Christmas break tomorrow and won't have access to internet until Wednesday next week.

**Comment by junghans** [comment]
@JoshuaSBrown, can you do a:
```
git remote update
git log --oneline origin/stable..origin/master
```
and check if I forgot anything.

**Comment by JoshuaSBrown** [comment]
Does that display all the commit that are different between the two branches? The only thing that I can see that I contributed that is missing is the addition of the beadstructure class

 *  added bead structure class which allows the comparison of structures of bonded beads

**Comment by junghans** [comment]
I just added things, which matter for the end user! Not sure if the bead structure change is actually visible.

**Review by JensWehner — APPROVED** [review]
LGTM, I cannot think of anything else.

**Comment by JoshuaSBrown** [comment]
@junghans than I have nothing to add.

**Pull request merged**
