### PR TITLE
Fix exclusions in csg_boltzmann

### LINKED ISSUE #624: csg_boltzmann exclusions creation broken
From https://groups.google.com/g/votca/c/1ECuIXGGMQE/m/0_0CmdQhBgAJ, somewhere between v1.5.1 and v1.6.3 we broke the exclusion creation in csg_boltzmann.

I will write a couple of tests against the v1.5.1 behaviour.

### PR DESCRIPTION
**Pull request by junghans**
These test pass with v1.5.1, but fail now. 
@JensWehner you refactored the `csg_boltzmann` code please have a look.

Fix #624.

See https://groups.google.com/g/votca/c/1ECuIXGGMQE/m/0_0CmdQhBgAJ for bug reporting.

### CODE REVIEW

**Comment by JensWehner** [comment]
@junghans can you try this?

**Comment by JensWehner** [comment]
@votca-bot format

**Comment by junghans** [comment]
@JensWehner works for me locally!

**Comment by junghans** [comment]
Hmm, I wasn't able to reproduce the error locally....

**Comment by JensWehner** [comment]
@junghans do you need anything from my side?

**Comment by junghans** [comment]
@JensWehner a review ;-)

**Review by JensWehner — APPROVED** [review]

**Pull request merged**
