### PR TITLE
added csg_dump test

### PR DESCRIPTION
**Pull request by junghans**
Related to #302 , test passed locally before #298.

### CODE REVIEW

**Comment by junghans** [comment]
It passed locally! Now let's merge it with stable (which includes #298) and we get a segfault!

**Comment by JoshuaSBrown** [comment]
This branch should be built with: https://github.com/votca/csgapps/pull/14

**Comment by junghans** [comment]
@JensWehner, is there a way to avoid the duplicated:
```
throw runtime_error("Error in dlpolytopologyreader.cc in trying to access bead type it does not exist.");
```

**Review by JensWehner — COMMENTED** [review]
I am not sure. This solution is rather hacky, as we do not yet understand the underlying cause. I do not know, I would return to it as a last resort. I also do not like all the error message, but I do not know what code changes would be necessary to fix this properly. I do not know. I ll look in the morning again

**Comment by JensWehner** [comment]
@junghans we can put the error into a function of the baseclass, to have it only once.

**Comment by junghans** [comment]
That sounds better!

**Comment by JoshuaSBrown** [comment]
I think part of the problem is the method name. GetOrCreateBeadType() I've created an issue here. I think refactoring the methods would help clarify how this method is being used:
https://github.com/votca/csg/issues/305

**Comment by JensWehner** [comment]
Concerning the use of std::runtime_error, errors should not be used to check for incorrect usage of code in my mind, but for wrong data. Asserts are for that.

**Comment by JoshuaSBrown** [comment]
@junghans would it be a good idea to setup travis to automatically build with branches that have the same name?

**Comment by junghans** [comment]
We had builds for all branches enabled in the past, but it triggered far too many builds! And without branch builds it is quite hard to figure out if there are two pull requests open pointing to branches with the same name!

Also this case happens only in very few cases and you can always triggered it manually!

**Pull request merged**
