### PR TITLE
add h5md build test

### PR DESCRIPTION
**Pull request by junghans**
Is it ok to merge?

### CODE REVIEW

**Comment by JensWehner** [comment]
Warum ich, ich hab doch von csg keine Ahnung. Christoph geben. :D

Lg Jens

2015-11-21 16:04 GMT+01:00 Christoph Junghans notifications@github.com:

**Comment by junghans** [comment]
Sorry, clicked wrong.....

**Comment by junghans** [comment]
@MrTheodor : ready to merge?

**Comment by jkrajniak** [comment]
I would say that it is ok although travis is still failing, nothing to do with h5md:
https://travis-ci.org/votca/csg/jobs/92592025

**Comment by junghans** [comment]
Re-triggered and fixed!

**Comment by junghans** [comment]
@spakin: Also see MrTheodor/csg#1 and https://bugs.launchpad.net/ubuntu/+source/hdf5/+bug/734889 on why we  need to build our own hdf5.

**Pull request merged**
