### PR TITLE
csg_stat: add error for too large interaction max

### PR DESCRIPTION
**Pull request by junghans**
Reported here: https://groups.google.com/d/topic/votca/erhqikA4_ns/discussion

### CODE REVIEW

**Review by JoshuaSBrown — APPROVED** [review]

**Comment by junghans** [comment]
@JoshuaSBrown can you have a look why this DeepCode bot craps out?

**Comment by JoshuaSBrown** [comment]
It looks like their server is hanging.

**Comment by JoshuaSBrown** [comment]
Retry DeepCode

**Comment by JoshuaSBrown** [comment]
"Retry DeepCode"

**Comment by JoshuaSBrown** [comment]
@junghans I have sent an email, but I would ignore it for now, nothing you have done should be causing problems.

**Comment by junghans** [comment]
```
 90/242 Test  #90: integration_Run_csg_stat_angular ...................***Failed    0.11 sec
begin to calculate distribution functions
# of bonded interactions: 0
# of non-bonded interactions: 1
I have 648 beads in 216 molecules
I have 216 beads in 216 molecules for the coarsegraining
Reading frame, timestep 0
an error occurred:
The max of interaction "CG-CG-CG" bigger is than half the box.
```

**Pull request merged**
