### PR TITLE
md -> rst

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@votca-bot changelog: Convert remaining md files to rst

**Review by DRosen285 — APPROVED** [review]
That works. 
But, this still pops up:

Running Sphinx v1.8.5
WARNING: extension 'recommonmark' has no setup() function; is it really a Sphinx extension module?

**Comment by junghans** [comment]
It might be from this line:
https://github.com/votca/votca/blob/5407c86f6e26e5962715e893dcc1eac2faa14a44/share/doc/conf.py.in#L13

**Comment by junghans** [comment]
I will drop the `md` parts when we merge this into `votca/votca`.

**Pull request merged**
