### PR TITLE
Added scaling option in optimizer_target_density.sh

### PR DESCRIPTION
**Pull request by t3rodrig**
A portion of settings.xml file:

``` xml
<cg>
     .
     .
     .
      <lammps>
        <!-- name of the table for lammps run -->
        <table>CG_CG.pot</table>
        <table_begin>2.0</table_begin>
        <table_bins>0.025</table_bins>
      </lammps>
      <optimizer>
        .
        .
        .
        <density>
          <target>CG-CG.density.tgt</target>
          <min>0</min>
          <max>80</max>
          <step>0.5</step>
          <axis>z</axis>
          <!-- Scaling factor for density -->
          <scale>1.66054</scale>
        </density>
        </optimizer>
     .
     .
     .
</cg>
```

### CODE REVIEW

**Comment by junghans** [comment]
Looks good to me.

Just so that I understand the background, your scaling only acts on the current density and not the target one, right? And why are you not using the `target_weights` to scale the difference?

**Comment by junghans** [comment]
And don't forget to update the copyright year in `*.sh`.

**Comment by t3rodrig** [comment]
Yes, I am only scaling the current density and not the target one. My target density is in g/cm^3, and I am using "units real" in lammps input file. An scaling factor is needed in order to get the right units of the current density profile [grams*mole^-1/A^3 -> g/cm^3]. Maybe I am wrong, but `target_weights` has a different use, or not?

**Comment by junghans** [comment]
Yeah, I was just thinking if you give the target density (e.g. `CG-CG.density.tgt`) in same units as what csg_stat calculated, you don't need an extra scale, however, I am fine with adding it!

**Pull request merged**
