### PR TITLE
more unit tests for interaction

### PR DESCRIPTION
**Pull request by JensWehner**
added unit tests for bond, angle, diheadral

### CODE REVIEW

**Review by JoshuaSBrown — COMMENTED** [review]
What's up with the formatting, the clang-format file should not be aligning the = as per our discussion a few months ago.

**Review by JoshuaSBrown — COMMENTED** [review]
Just a heads up I recently found out that calling endl calls flush every time and that it is preferred to call "\n" explicitly in place of std::endl; unless you are really wanting to flush the buffer.

**Review by JoshuaSBrown — CHANGES_REQUESTED** [review]
Figure out what is wrong with the formatting.

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
@JoshuaSBrown for a unit test the flushing of the buffer doesn't matter much, plus the output of tests gets redirected to a file with through buffering the filesystem anyhow.

**Comment by JoshuaSBrown** [comment]
Yes, I it doesn't matter in this case, but I found that out the other day and thought it was a useful thing to know. You could potentially take a performance hit when outputting a lot of data... maybe.

**Comment by junghans** [comment]
So can we merge this?

**Review by JoshuaSBrown — APPROVED** [review]

**Pull request merged**
