### PR TITLE
Stable fixes

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by JensWehner — DISMISSED** [review]
LGTM

**Comment by junghans** [comment]
```
 90/242 Test  #90: integration_Run_csg_stat_angular ...................***Failed    0.11 sec
begin to calculate distribution functions
# of bonded interactions: 0
# of non-bonded interactions: 1
I have 648 beads in 216 molecules
I have 216 beads in 216 molecules for the coarsegraining
Reading frame, timestep 0
an error occurred:
The max of interaction "CG-CG-CG" bigger is than half the box.
```
has to think about this some more.

**Comment by junghans** [comment]
I backed out #512 again!

**Review by JensWehner — APPROVED** [review]
So grmacs 2021 has the headers again? Nice

**Comment by junghans** [comment]
> So grmacs 2021 has the headers again? Nice

Yeah there is an option.

**Pull request merged**
